### ISSUE TITLE
Text is right aligned in the chat bubble

### ISSUE THREAD

**Issue by agazso** [logos-innovation-lab/waku-objects-playground#252]
The text is right aligned in the chat bubble and it is a bit unexpected, because in the text input it is left aligned. I tried out it in other chat apps and usually the text in the text bubble is also left aligned.

This is Waku Play:
![Screenshot from 2023-08-03 14-12-40](https://github.com/logos-innovation-lab/waku-objects-playground/assets/230163/50532a1b-2fa7-4611-90b2-a63bc0de6326)

This is Signal:
![Screenshot from 2023-08-03 14-13-25](https://github.com/logos-innovation-lab/waku-objects-playground/assets/230163/784faef7-d000-4e8a-b5b4-77ca5188803f)

**Comment by sugarpusher** [comment]
@agazso 
This is according to the design
https://www.sketch.com/s/288cf5cf-ed53-4c43-bfb9-88d783cb3d22/a/OeRlPDR

**Comment by agazso** [comment]
@david-gauquelin Another illustration why it is strange:

![Screenshot from 2023-08-03 22-39-28](https://github.com/logos-innovation-lab/waku-objects-playground/assets/230163/b0d8d5a4-b6b3-4434-a625-60f7cd2723bf)

**Comment by david-gauquelin** [comment]
This is my bad. In the initial design the text is left-aligned https://www.sketch.com/s/98c659f4-66e3-4800-8c2b-ebc5125c5090/a/DE4DOvq then I made a mistake while making the mock-ups, sorry. So please let's do left-aligned.

**Comment by david-gauquelin** [comment]
also in the image that @agazso shared above there seem to be a line-break issue. I'm not sure why the word "wallet" is on one line alone?

**Comment by sugarpusher** [comment]
@david-gauquelin From the text it seems that there's an intentional line break after the word wallet, but I see @agazso 's point regarding the unbalanced text.

This is not something that can be addressed via css - except by using the experimental `text-wrap: balance;`, which isn't fully supported currently.

The other issue with using `text-wrap: balance;` is that it doesn't change the inline size of the element, so you'd end up with a full size (3/4) bubble but with content that only spans part of that (see image below).

Anything else that I can use (calculations, percentages, ch units, etc) will not work because css doesn't know how long the string is and when to break it or not. 

I suggest that we address this via javascript (if we choose to).

<img width="490" alt="Screenshot 2023-08-04 at 8 27 23 AM" src="https://github.com/logos-innovation-lab/waku-objects-playground/assets/16855117/0482133d-7824-431b-ac18-82e210e632c1">

**Comment by agazso** [comment]
> @david-gauquelin From the text it seems that there's an intentional line break after the word wallet, but I see @agazso 's point regarding the unbalanced text.

Just to clarify, indeed there is a line break _after_ the word `wallet` and there is no line break _before_ it.

**Comment by agazso** [comment]
As far as I am concerned #262 fixes this issue
